apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: academic-puffin-go 
  janus-idp.io/tekton: academic-puffin-go
  backstage.io/kubernetes-id: academic-puffin-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: academic-puffin-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  